name: AmongFriends
description: Find friends to play with  ✌️
android: https://play.google.com/store/apps/details?id=com.baryaa.amongfriendsfind
iOS: https://apps.apple.com/app/id1533580691
# screenshots:
#   - 1.png
#   - 2.png
#   - 3.png
